// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Pz_a8e6Kl6X_dtoU1DAybrGXIC0TjVE',
    appId: '1:70501463475:web:d038628a76d98fc40b07c6',
    messagingSenderId: '70501463475',
    projectId: 'bappfirebase',
    authDomain: 'bappfirebase.firebaseapp.com',
    storageBucket: 'bappfirebase.firebasestorage.app',
    measurementId: 'G-SWPBW7PBD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBApWWMlnErpzVzdL7CLP_eO2l44T96RjI',
    appId: '1:70501463475:android:a2762ea04815e91c0b07c6',
    messagingSenderId: '70501463475',
    projectId: 'bappfirebase',
    storageBucket: 'bappfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWZHHJcNgfVQxWGI0ijDu5botTMjqhZiw',
    appId: '1:70501463475:ios:46defa255642b4460b07c6',
    messagingSenderId: '70501463475',
    projectId: 'bappfirebase',
    storageBucket: 'bappfirebase.firebasestorage.app',
    iosBundleId: 'com.example.bapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWZHHJcNgfVQxWGI0ijDu5botTMjqhZiw',
    appId: '1:70501463475:ios:46defa255642b4460b07c6',
    messagingSenderId: '70501463475',
    projectId: 'bappfirebase',
    storageBucket: 'bappfirebase.firebasestorage.app',
    iosBundleId: 'com.example.bapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Pz_a8e6Kl6X_dtoU1DAybrGXIC0TjVE',
    appId: '1:70501463475:web:3502e0bf2c01a82d0b07c6',
    messagingSenderId: '70501463475',
    projectId: 'bappfirebase',
    authDomain: 'bappfirebase.firebaseapp.com',
    storageBucket: 'bappfirebase.firebasestorage.app',
    measurementId: 'G-4K69802E3B',
  );
}
